@startuml

class EmailBuilder {
  -recipients : Set
  -title : String
  -greeting : String
  -mainText : String
  -closing : String
  +addRecipient() : EmailBuilder
  +removeRecipient() : EmailBuilder
  +setTitle() : EmailBuilder
  +setGreeting() : EmailBuilder
  +setMainText() : EmailBuilder
  +setClosing() : EmailBuilder
  +create() : Email
  +commaSeparatedRecipients() : String
}

class Email {
  -title : String
  -recipients : String
  -message : String
  +Email()
  +getTitle() : String
  +getRecipients() : String
  +getMessage() : String
  +send() : void
}

EmailBuilder -right-> Email

@enduml